import { afterEach,describe,expect,it,vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { collectAmazon,collectApple,collectorInternals } from '../src/collectors.js';
import { collectBrightDataRetailers,extractBrightDataProduct,type BrightDataTarget } from '../src/brightdata.js';

const fixture=(name:string)=>readFileSync(new URL(`fixtures/${name}`,import.meta.url),'utf8');

afterEach(()=>vi.unstubAllGlobals());
describe('collector failure handling',()=>{
  it('records HTTP failures instead of fabricating observations',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('blocked',{status:403})));const r=await collectAmazon();expect(r.status).toBe('failed');expect(r.observations).toHaveLength(0);expect(r.errors[0]).toContain('HTTP 403')});
  it('records malformed payloads as a failed run',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('<html>'+('x'.repeat(600))+'</html>',{status:200})));const r=await collectApple();expect(r.status).toBe('failed');expect(r.errors[0]).toContain('bootstrap not found')});
  it('extracts only the primary new-condition Amazon buy box',()=>{const html=`<html><body><span id="productTitle">Apple 2026 MacBook Air 13-inch Laptop with M5 chip, 13.6-inch, 16GB Unified Memory, 512GB SSD</span><div id="corePriceDisplay_desktop_feature_div"><span id="apex-pricetopay-accessibility-label">$1,299.00</span></div><div id="sfsb_accordion_head">Ships from: Amazon.com Sold by: Amazon.com</div><input id="add-to-cart-button"></body></html>`;expect(collectorInternals.parseAmazonPdp(html)).toEqual({title:'Apple 2026 MacBook Air 13-inch Laptop with M5 chip, 13.6-inch, 16GB Unified Memory, 512GB SSD',raw_price:'$1,299.00',seller:'Amazon.com',ships_from:'Amazon.com',available:true})});
  it('rejects a third-party Amazon marketplace buy box',async()=>{const html=`<html><body>${'x'.repeat(600)}<span id="productTitle">Apple 2026 MacBook Air 13-inch Laptop with M5 chip, 13.6-inch, 16GB Unified Memory, 512GB SSD</span><div id="corePriceDisplay_desktop_feature_div"><span id="apex-pricetopay-accessibility-label">$999.00</span></div><div id="sfsb_accordion_head">Ships from: Amazon Sold by: Unknown Deals LLC</div><input id="add-to-cart-button"></body></html>`;vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const r=await collectAmazon();expect(r.status).toBe('failed');expect(r.observations).toHaveLength(0);expect(r.errors[0]).toContain('Rejected non-Amazon seller')});
  it('keeps saved Apple and Best Buy source contracts readable',()=>{const apple=collectorInternals.parseAppleBootstrap(fixture('apple-product-selection.html'));expect(apple.products[0].btrOrFdPartNumber).toBe('TEST1');const bestBuy=collectorInternals.parseBestBuyTransport(fixture('bestbuy-search.html'));expect(bestBuy[0]).toMatchObject({skuId:'123',brand:'Apple'})});
  it('extracts schema.org product evidence from a Bright Data response',()=>{const target:BrightDataTarget={merchant_id:'example',merchant_name:'Example Electronics',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};expect(extractBrightDataProduct(fixture('brightdata-product.html'),target)).toMatchObject({raw_price:'$1099.00',seller:'Example Electronics',available:true,extraction_path:'json-ld'})});
  it('quarantines an unapproved marketplace seller without reporting a successful refresh or match',async()=>{const html=fixture('brightdata-product.html').replace('Example Electronics','Unknown Marketplace LLC');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('failed');expect(result.matched_products).toBe(0);expect(result.observations[0]?.collection_status).toBe('rejected_policy');expect(result.errors[0]).toContain('Rejected seller of record')});
  it('does not substitute product brand for missing seller evidence',()=>{const html=fixture('brightdata-product.html').replace(',"seller":{"@type":"Organization","name":"Example Electronics"}','').replace('"sku":"TEST-SKU"','"sku":"TEST-SKU","brand":{"@type":"Brand","name":"Apple"}');const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Apple']};expect(extractBrightDataProduct(html,target).seller).toBe('')});
  it('does not turn generic page markers into seller-of-record evidence',async()=>{const html=fixture('brightdata-product.html').replace(',"seller":{"@type":"Organization","name":"Example Electronics"}','').replace('</body>','<p>Authorized Dealer — B&H Photo Video</p></body>');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const target:BrightDataTarget={merchant_id:'bh-photo',merchant_name:'B&H Photo',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['B&H Photo']};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('failed');expect(result.matched_products).toBe(0);expect(result.observations[0]?.collection_status).toBe('rejected_policy');expect((result.observations[0]!.raw_payload as any).seller_evidence).toBe('missing')});
  it('accepts an approved retailer-owned PDP and labels inferred seller evidence',async()=>{const html=fixture('brightdata-product.html').replace(',"seller":{"@type":"Organization","name":"Example Electronics"}','');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const target:BrightDataTarget={merchant_id:'bh-photo',merchant_name:'B&H Photo',url:'https://www.bhphotovideo.com/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['B&H Photo'],allow_implicit_first_party:true};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('success');expect(result.matched_products).toBe(1);expect(result.observations[0]?.collection_status).toBe('success');expect((result.observations[0]!.raw_payload as any).seller_of_record).toBe('B&H Photo');expect((result.observations[0]!.raw_payload as any).seller_evidence).toBe('retailer-owned-pdp-inferred')});
  it('does not infer first-party seller identity on an unapproved host',async()=>{const html=fixture('brightdata-product.html').replace(',"seller":{"@type":"Organization","name":"Example Electronics"}','');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const target:BrightDataTarget={merchant_id:'bh-photo',merchant_name:'B&H Photo',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['B&H Photo'],allow_implicit_first_party:true};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('failed');expect(result.observations[0]?.collection_status).toBe('rejected_policy');expect((result.observations[0]!.raw_payload as any).seller_evidence).toBe('missing')});
  it('reports partial only when a run contains both an accepted result and a rejection',async()=>{const good=fixture('brightdata-product.html');const rejected=good.replace('Example Electronics','Unknown Marketplace LLC');const fetchMock=vi.fn().mockResolvedValueOnce(new Response(good,{status:200})).mockResolvedValueOnce(new Response(rejected,{status:200}));vi.stubGlobal('fetch',fetchMock);const base:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};const result=await collectBrightDataRetailers([base,{...base,url:'https://example.test/rejected'}],'token','zone','');expect(result.status).toBe('partial');expect(result.matched_products).toBe(1);expect(result.observations.map(item=>item.collection_status)).toEqual(['success','rejected_policy'])});
  it('does not report success when every parsed page is an unmatched product',async()=>{const html=fixture('brightdata-product.html').replace('Apple MacBook Air 13-inch M5 16GB Memory 512GB SSD','Ceramic coffee mug');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('failed');expect(result.matched_products).toBe(0);expect(result.observations[0]?.collection_status).toBe('unmatched')});
  it('uses saved HTML rules for rendered retailer state',()=>{const html='<title>Walmart</title><script>{"productName":"Apple AirPods Pro 3","currentPrice":{"price":199.99},"availabilityStatus":{"display":"In stock","value":"IN_STOCK"},"sellerDisplayName":"Walmart.com","motorOilType":null,"model":"MFHP4LL/A"}</script>';const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://www.walmart.com/ip/example',expected_product_id:'apple-airpods-pro-3',source_product_id:'MFHP4LL/A',accepted_sellers:['Walmart.com'],html_patterns:{title:'"productName":"([^"]+)"',price:'"currentPrice":\\{"price":([0-9.]+)',availability:'"availabilityStatus":\\{"display":"([^"]+)","value":"IN_STOCK"',seller:'"sellerDisplayName":"([^"]+)"',sku:'"motorOilType":null,"model":"([^"]+)"'}};expect(extractBrightDataProduct(html,target)).toMatchObject({title:'Apple AirPods Pro 3',raw_price:'$199.99',available:true,seller:'Walmart.com',source_product_id:'MFHP4LL/A',extraction_path:'saved-html-rules'})});
  it('uses saved markdown rules when Bright Data cannot return HTML',()=>{const markdown='PRICEMCP_BRIGHTDATA_MARKDOWN\nSource URL: https://www.target.com/p/example\nApple AirPods Pro 3 Wireless Earbuds\n$199.99 reg $249.99\nPickup Ready within 2 hours\nTCIN: 85978609';const target:BrightDataTarget={merchant_id:'target',merchant_name:'Target',url:'https://www.target.com/p/example',expected_product_id:'apple-airpods-pro-3',source_product_id:'85978609',accepted_sellers:['Target'],markdown_patterns:{title:'^(Apple AirPods Pro 3 Wireless Earbuds)$',price:'^\\$(199\\.99)',availability:'Pickup (Ready within [^\\n]+)',sku:'TCIN: (85978609)'}};expect(extractBrightDataProduct(markdown,target)).toMatchObject({title:'Apple AirPods Pro 3 Wireless Earbuds',raw_price:'$199.99',available:true,source_product_id:'85978609',extraction_path:'saved-markdown-rules'})});
  it('does not accept a locally supplied request URL as retailer SKU evidence',()=>{const body='PRICEMCP_BRIGHTDATA_MARKDOWN\nSource URL: https://www.target.com/p/item/-/A-85978609\nApple AirPods Pro 3 Wireless Earbuds\n$219.99\nPickup Ready within 2 hours';const target:BrightDataTarget={merchant_id:'target',merchant_name:'Target',url:'https://www.target.com/p/item/-/A-85978609',expected_product_id:'apple-airpods-pro-3',source_product_id:'85978609',accepted_sellers:['Target'],markdown_patterns:{title:'^(Apple AirPods Pro 3 Wireless Earbuds)$',price:'^\\$([0-9]+\\.[0-9]{2})$',availability:'Pickup (Ready within [^\\n]+)',sku:'TCIN: (85978609)'}};expect(()=>extractBrightDataProduct(body,target)).toThrow('did not produce title, price, and SKU')});
  it('requires positive availability evidence',()=>{const html=fixture('brightdata-product.html').replace('"availability":"https://schema.org/InStock",','');const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};expect(extractBrightDataProduct(html,target).available).toBe(false)});
  it('rejects unsupported currencies instead of parsing them as USD',async()=>{const html=fixture('brightdata-product.html').replace('"priceCurrency":"USD"','"priceCurrency":"EUR"');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(html,{status:200})));const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('failed');expect(result.errors[0]).toContain('Unsupported currency: EUR')});
  it('requires page SKU evidence to match the configured retailer SKU',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(fixture('brightdata-product.html'),{status:200})));const target:BrightDataTarget={merchant_id:'walmart',merchant_name:'Walmart',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'OTHER-SKU',accepted_sellers:['Example Electronics']};const result=await collectBrightDataRetailers([target],'token','zone','');expect(result.status).toBe('failed');expect(result.errors[0]).toContain('Rejected retailer SKU')});
  it('rejects unknown merchants before making a network request',async()=>{const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);const target:BrightDataTarget={merchant_id:'not-in-catalog',merchant_name:'Unknown',url:'https://example.test/p',expected_product_id:'apple-macbook-air-m5-13-16-512',source_product_id:'TEST-SKU',accepted_sellers:['Example Electronics']};const result=await collectBrightDataRetailers([target],'token','zone');expect(result.status).toBe('failed');expect(result.errors[0]).toContain('Unknown merchant');expect(fetchMock).not.toHaveBeenCalled()});
});
