import { describe, expect, it } from 'vitest';
import { openDatabase, seed, appendObservation, getOffers, bestPrice, history, searchProducts, recordCollection } from '../src/db.js';
import { extractAttributes, freshness, matchProduct, parsePrice } from '../src/normalize.js';
import { catalog } from '../src/catalog.js';
import type { RawObservation } from '../src/types.js';

const observation=(overrides:Partial<RawObservation>={}):RawObservation=>({source:'test',source_method:'fixture',merchant_id:'apple',source_product_id:'sku-1',url:'https://example.test/product',observed_at:new Date().toISOString(),title:'Apple MacBook Air 13-inch M5 16GB Memory 512GB SSD',raw_price:'$1,299.00',currency:'USD',price_minor:129900,shipping_minor:0,available:true,condition:'new',matched_product_id:'apple-macbook-air-m5-13-16-512',match_confidence:.99,collection_status:'success',...overrides});
const database=()=>{const db=openDatabase(':memory:');seed(db);return db};

describe('normalization',()=>{
  it('parses US prices to integer minor units',()=>expect(parsePrice('$1,299.95')).toBe(129995));
  it('rejects missing, negative, and unsupported currency prices',()=>{expect(()=>parsePrice('free')).toThrow();expect(()=>parsePrice('-1')).toThrow();expect(()=>parsePrice('10','EUR')).toThrow()});
  it('extracts comparable variant attributes',()=>expect(extractAttributes('M5 13-inch 16GB Unified Memory 1TB SSD')).toEqual({chip:'M5',display_inches:13,memory_gb:16,storage_gb:1024}));
  it('matches exact variants and rejects conflicting storage',()=>{expect(matchProduct('MacBook Air 13-inch M5 16GB Memory 512GB SSD',catalog).product?.id).toBe('apple-macbook-air-m5-13-16-512');expect(matchProduct('MacBook Air 13-inch M5 16GB Memory 2TB SSD',catalog).product).toBeNull()});
  it('matches accessory families only when their defining generation/features agree',()=>{expect(matchProduct('Apple AirPods Pro 3, Wireless Active Noise Cancelling Earbuds',catalog).product?.id).toBe('apple-airpods-pro-3');expect(matchProduct('Apple AirPods 4 with Active Noise Cancellation',catalog).product?.id).toBe('apple-airpods-4-anc');expect(matchProduct('Protective case for Apple AirPods Pro',catalog).product).toBeNull()});
  it('classifies freshness boundaries',()=>{const now=new Date('2026-01-02T00:00:00Z');expect(freshness('2026-01-01T23:30:01Z',now).freshness_status).toBe('fresh');expect(freshness('2026-01-01T20:00:00Z',now).freshness_status).toBe('recent');expect(freshness('2026-01-01T12:00:00Z',now).freshness_status).toBe('aging');expect(freshness('2025-12-31T00:00:00Z',now).freshness_status).toBe('stale')});
});

describe('storage and ranking',()=>{
  it('keeps duplicate-SKU history append-only while projecting one current offer',()=>{const db=database();appendObservation(db,null,observation());appendObservation(db,null,observation({price_minor:119900,raw_price:'$1,199.00'}));expect((db.prepare('select count(*) n from price_observations').get() as any).n).toBe(2);expect(getOffers(db,'apple-macbook-air-m5-13-16-512')).toHaveLength(1);expect(getOffers(db,'apple-macbook-air-m5-13-16-512')[0].total_minor).toBe(119900)});
  it('refreshes a merchant projection without retaining superseded color SKUs',()=>{const db=database();recordCollection(db,{source:'apple-us',method:'fixture',status:'success',observations:[observation({source_product_id:'silver-part'})],matched_products:1,errors:[]});recordCollection(db,{source:'apple-us',method:'fixture',status:'success',observations:[observation({source_product_id:'blue-part'})],matched_products:1,errors:[]});expect(getOffers(db,'apple-macbook-air-m5-13-16-512')).toHaveLength(1);expect(getOffers(db,'apple-macbook-air-m5-13-16-512')[0].source_product_id).toBe('blue-part');expect((db.prepare('select count(*) n from price_observations').get() as any).n).toBe(2)});
  it('normalizes merchants and separates cheapest from trusted',()=>{const db=database();db.prepare('INSERT INTO merchants VALUES(?,?,?,?,?,?,?,?,?)').run('marketplace-test','Marketplace seller',0,0,.4,'marketplace',.5,1,'test-only unverified seller');appendObservation(db,null,observation());appendObservation(db,null,observation({merchant_id:'marketplace-test',source_product_id:'marketplace-sku',price_minor:99900,shipping_minor:null,raw_price:'$999'}));const ranked=bestPrice(db,'apple-macbook-air-m5-13-16-512');expect(ranked.cheapest_offer.merchant_id).toBe('marketplace-test');expect(ranked.best_trusted_offer.merchant_id).toBe('apple')});
  it('does not rank unavailable offers',()=>{const db=database();appendObservation(db,null,observation({available:false}));expect(bestPrice(db,'apple-macbook-air-m5-13-16-512').cheapest_offer).toBeNull()});
  it('replaces an older in-stock projection when the same SKU becomes unavailable',()=>{const db=database();appendObservation(db,null,observation());appendObservation(db,null,observation({available:false,collection_status:'unavailable'}));expect(getOffers(db,'apple-macbook-air-m5-13-16-512')[0].available).toBe(false);expect(bestPrice(db,'apple-macbook-air-m5-13-16-512').cheapest_offer).toBeNull()});
  it('filters stale evidence by requested maximum age',()=>{const db=database();appendObservation(db,null,observation({observed_at:new Date(Date.now()-25*3600_000).toISOString()}));expect(getOffers(db,'apple-macbook-air-m5-13-16-512',24)).toHaveLength(0);expect(bestPrice(db,'apple-macbook-air-m5-13-16-512').cheapest_offer).toBeNull()});
  it('computes previous, change, and 30-day range',()=>{const db=database();appendObservation(db,null,observation({observed_at:new Date(Date.now()-3600_000).toISOString(),price_minor:139900}));appendObservation(db,null,observation({source_product_id:'sku-2',price_minor:129900}));const h=history(db,'apple-macbook-air-m5-13-16-512');expect(h.current.normalized_total_minor).toBe(129900);expect(h.previous.normalized_total_minor).toBe(139900);expect(h.change_minor).toBe(-10000);expect(h.low_30d_minor).toBe(129900);expect(h.high_30d_minor).toBe(139900)});
  it('resolves the requested demo SKU deterministically without substituting M5',()=>expect(searchProducts(database(),'MacBook Air M4 16GB 256GB',1)[0].id).toBe('apple-macbook-air-m4-13-16-256'));
});
