import { afterEach,describe,expect,it,vi } from 'vitest';
import { appendObservation,bestPrice,getProduct,history,openDatabase,searchProducts,seed } from '../src/db.js';
import { demoCatalog,demoDataset,demoMerchants,demoOfficialPrices } from '../src/demo-catalog.js';
import { buildApp } from '../src/server.js';
import type { RawObservation } from '../src/types.js';

const database=()=>{const db=openDatabase(':memory:');seed(db,demoCatalog,demoMerchants);return db};
const obs=(merchant_id:string,price_minor:number,overrides:Partial<RawObservation>={}):RawObservation=>({source:'demo-test',source_method:'synthetic_fixture',merchant_id,source_product_id:`${merchant_id}-sku`,url:'https://example.invalid/demo',observed_at:new Date().toISOString(),title:'Samsung 990 PRO NVMe SSD 2TB',raw_price:`$${(price_minor/100).toFixed(2)}`,currency:'USD',price_minor,shipping_minor:0,available:true,condition:'new',matched_product_id:'demo-samsung-990-pro-2tb',match_confidence:1,collection_status:'success',dataset:demoDataset,synthetic:true,raw_payload:{synthetic:true,dataset:demoDataset},...overrides});

afterEach(()=>vi.unstubAllEnvs());
describe('synthetic demo dataset',()=>{
  it('seeds exactly 31 clearly marked benchmark products',()=>{const db=database();expect((db.prepare('select count(*) n from products').get() as any).n).toBe(31);expect(getProduct(db,'demo-samsung-990-pro-2tb')).toMatchObject({dataset:demoDataset,synthetic:true})});
  it.each(['M4','M5','M6'])('resolves Mac mini %s without generation substitution',(chip)=>{const result=searchProducts(database(),`Mac mini ${chip} 16GB 256GB`,3);expect(result[0]).toMatchObject({id:`demo-apple-mac-mini-${chip.toLowerCase()}-16-256`,family:'Mac mini',attributes:{chip}});expect(result.filter(x=>x.family==='Mac mini'&&x.attributes.chip!==chip)).toHaveLength(0)});
  it('separates cheapest marketplace, trusted, membership, and official offers',()=>{const db=database(),base=demoOfficialPrices['demo-samsung-990-pro-2tb']!;appendObservation(db,null,obs('demo-brand-direct',base));appendObservation(db,null,obs('demo-northstar',Math.round(base*.89)));appendObservation(db,null,obs('demo-club-warehouse',Math.round(base*.86),{membership_required:true}));appendObservation(db,null,obs('demo-marketsquare',Math.round(base*.8)));const ranked=bestPrice(db,'demo-samsung-990-pro-2tb');expect(ranked.cheapest_offer.merchant_id).toBe('demo-marketsquare');expect(ranked.best_trusted_offer.merchant_id).toBe('demo-northstar');expect(ranked.best_membership_offer.merchant_id).toBe('demo-club-warehouse');expect(ranked.official_price.merchant_id).toBe('demo-brand-direct')});
  it('uses only the controlled history series for synthetic deal metrics',()=>{const db=database();appendObservation(db,null,obs('demo-marketsquare',10000));appendObservation(db,null,obs('demo-northstar',18000,{source_method:'synthetic_history_fixture',observed_at:new Date(Date.now()-86400_000).toISOString()}));appendObservation(db,null,obs('demo-northstar',16000,{source_method:'synthetic_history_fixture'}));const h=history(db,'demo-samsung-990-pro-2tb');expect(h.points).toHaveLength(2);expect(h.current.normalized_total_minor).toBe(16000);expect(h.previous.normalized_total_minor).toBe(18000)});
  it('renders a persistent warning and marks API results synthetic',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);const app=buildApp(database());const page=await app.inject({url:'/'});expect(page.body).toContain('DEMO DATA — SYNTHETIC PRICES — NOT LIVE OR PURCHASABLE');const api=await app.inject({url:'/v1/search?q=Samsung%20990%20PRO%202TB'});expect(api.json()).toMatchObject({dataset:demoDataset,synthetic:true});expect(api.json().results[0]).toMatchObject({synthetic:true,dataset:demoDataset});await app.close()});
});
