import { afterEach,describe,expect,it,vi } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { appendObservation,bestPrice,getProduct,history,openDatabase,searchProducts,seed } from '../src/db.js';
import { demoCatalog,demoDataset,demoMerchants,demoOfficialPrices } from '../src/demo-catalog.js';
import { createMcpServer } from '../src/mcp.js';
import { buildApp } from '../src/server.js';
import { parseNaturalPriceQuery } from '../src/price-search.js';
import type { RawObservation } from '../src/types.js';

const database=()=>{const db=openDatabase(':memory:');seed(db,demoCatalog,demoMerchants);return db};
const obs=(merchant_id:string,price_minor:number,overrides:Partial<RawObservation>={}):RawObservation=>({source:'demo-test',source_method:'synthetic_fixture',merchant_id,source_product_id:`${merchant_id}-sku`,url:'https://example.invalid/demo',observed_at:new Date().toISOString(),title:'Samsung 990 PRO NVMe SSD 2TB',raw_price:`$${(price_minor/100).toFixed(2)}`,currency:'USD',price_minor,shipping_minor:0,available:true,condition:'new',matched_product_id:'demo-samsung-990-pro-2tb',match_confidence:1,collection_status:'success',dataset:demoDataset,synthetic:true,raw_payload:{synthetic:true,dataset:demoDataset},...overrides});

afterEach(()=>vi.unstubAllEnvs());
describe('synthetic demo dataset',()=>{
  it('seeds exactly 31 clearly marked benchmark products',()=>{const db=database();expect((db.prepare('select count(*) n from products').get() as any).n).toBe(31);expect(getProduct(db,'demo-samsung-990-pro-2tb')).toMatchObject({dataset:demoDataset,synthetic:true})});
  it.each(['M4','M5','M6'])('resolves Mac mini %s without generation substitution',(chip)=>{const result=searchProducts(database(),`Mac mini ${chip} 16GB 256GB`,3);expect(result[0]).toMatchObject({id:`demo-apple-mac-mini-${chip.toLowerCase()}-16-256`,family:'Mac mini',attributes:{chip}});expect(result.filter(x=>x.family==='Mac mini'&&x.attributes.chip!==chip)).toHaveLength(0)});
  it('separates cheapest marketplace, trusted, membership, and official offers',()=>{const db=database(),base=demoOfficialPrices['demo-samsung-990-pro-2tb']!;appendObservation(db,null,obs('demo-brand-direct',base));appendObservation(db,null,obs('demo-northstar',Math.round(base*.89)));appendObservation(db,null,obs('demo-club-warehouse',Math.round(base*.86),{membership_required:true}));appendObservation(db,null,obs('demo-marketsquare',Math.round(base*.8)));const ranked=bestPrice(db,'demo-samsung-990-pro-2tb');expect(ranked.cheapest_offer.merchant_id).toBe('demo-marketsquare');expect(ranked.best_trusted_offer.merchant_id).toBe('demo-northstar');expect(ranked.best_membership_offer.merchant_id).toBe('demo-club-warehouse');expect(ranked.official_price.merchant_id).toBe('demo-brand-direct')});
  it('keeps stale and membership-only offers out of the default trusted MCP comparison',async()=>{const db=database(),base=demoOfficialPrices['demo-samsung-990-pro-2tb']!;appendObservation(db,null,obs('demo-brand-direct',base));appendObservation(db,null,obs('demo-northstar',Math.round(base*.89)));appendObservation(db,null,obs('demo-club-warehouse',Math.round(base*.86),{membership_required:true}));appendObservation(db,null,obs('demo-harbor',Math.round(base*.75),{observed_at:new Date(Date.now()-30*3_600_000).toISOString()}));const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();const server=createMcpServer(db);const client=new Client({name:'demo-test',version:'1'});await server.connect(serverTransport);await client.connect(clientTransport);const called=await client.callTool({name:'compare_prices',arguments:{product_id:'demo-samsung-990-pro-2tb',trusted_only:true}});const data=called.structuredContent as any;expect(data.offers.map((offer:any)=>offer.merchant.merchant_id)).toEqual(['demo-northstar','demo-brand-direct']);expect(data).toMatchObject({include_membership:false,max_age_hours:6});await client.close();await server.close()});
  it('uses only the controlled history series for synthetic deal metrics',()=>{const db=database();appendObservation(db,null,obs('demo-marketsquare',10000));appendObservation(db,null,obs('demo-northstar',18000,{source_method:'synthetic_history_fixture',observed_at:new Date(Date.now()-86400_000).toISOString()}));appendObservation(db,null,obs('demo-northstar',16000,{source_method:'synthetic_history_fixture'}));const h=history(db,'demo-samsung-990-pro-2tb');expect(h.points).toHaveLength(2);expect(h.current.normalized_total_minor).toBe(16000);expect(h.previous.normalized_total_minor).toBe(18000)});
  it('renders a persistent warning, universal judge flows, focused matches, and synthetic API provenance',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);const app=buildApp(database());const page=await app.inject({url:'/'});expect(page.body).toContain('DEMO DATA — SYNTHETIC PRICES — NOT LIVE OR PURCHASABLE');expect(page.body).toContain('Try the universal price layer');expect(page.body).toContain('I need a Mac mini.');expect(page.body).toContain('Washington → Berlin');expect(page.body).toContain('No ads · no sponsored ranking');const exact=await app.inject({url:'/?q=iPhone%2017%20Pro%20256GB'});expect(exact.body).toContain('iPhone 17 Pro 256GB');expect(exact.body).not.toContain('iPad Pro 11-inch');const api=await app.inject({url:'/v1/search?q=Samsung%20990%20PRO%202TB'});expect(api.json()).toMatchObject({dataset:demoDataset,synthetic:true});expect(api.json().results[0]).toMatchObject({synthetic:true,dataset:demoDataset});await app.close()});
  it('recognizes a complete natural-language flight query and exposes the same normalized demo quote through REST and web',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);const query='Flight Washington to Berlin 2026-09-18 2026-09-25';expect(parseNaturalPriceQuery(query)).toMatchObject({type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'});const app=buildApp(database());const api=await app.inject({method:'POST',url:'/v1/search-price',payload:{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'}});expect(api.json()).toMatchObject({status:'ok',synthetic:true,dataset:demoDataset,best_offer:{provider:{name:'United'},quote:{total_minor:61200,currency:'USD'}}});expect(api.json().offers).toHaveLength(3);const page=await app.inject({url:`/?q=${encodeURIComponent(query)}`});expect(page.body).toContain('WAS → BER');expect(page.body).toContain('$612.00');expect(page.body).toContain('DEMO DATA');await app.close()});
  it('does not invent missing flight fields, flip routes, or apply the fixture to another itinerary',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);expect(parseNaturalPriceQuery('find flight prices')).toMatchObject({type:'incomplete',intent:'flight'});expect(parseNaturalPriceQuery('Fly from Washington to Berlin 2026-09-18')).toMatchObject({type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18'});expect(parseNaturalPriceQuery('Flight Berlin to Washington 2026-09-18 2026-09-25')).toMatchObject({type:'flight',origin:'BER',destination:'WAS'});expect(parseNaturalPriceQuery('Flight London to Berlin 2026-09-18')).toMatchObject({type:'incomplete',missing:['origin/destination']});expect(parseNaturalPriceQuery('Flight Washington to Berlin 2026-02-31')).toMatchObject({type:'incomplete',missing:['valid flight date']});expect(parseNaturalPriceQuery('Flight Washington to Berlin 2026-09-18 2026-09-25 2026-10-01')).toMatchObject({type:'incomplete',missing:['unambiguous flight dates']});const app=buildApp(database());const incomplete=await app.inject({url:'/?q=find%20flight%20prices'});expect(incomplete.body).toContain('PriceMCP did not invent an itinerary');const unrelated=await app.inject({method:'POST',url:'/v1/search-price',payload:{type:'flight',origin:'BOS',destination:'TYO',departure_date:'2026-09-18',return_date:'2026-09-25',cabin:'business',adults:9}});expect(unrelated.json()).toMatchObject({status:'no_match',offers:[],synthetic:true});await app.close()});
  it('does not promote a broad product query or a matched product without offers',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);const app=buildApp(database());const broad=await app.inject({method:'POST',url:'/v1/search-price',payload:{type:'product',query:'Mac mini'}});expect(broad.json()).toMatchObject({status:'no_match',best_offer:null,subject:{type:'product'}});const exact=await app.inject({method:'POST',url:'/v1/search-price',payload:{type:'product',query:'Mac mini M4 16GB 256GB'}});expect(exact.json()).toMatchObject({status:'no_match',best_offer:null,offers:[]});await app.close()});
  it('shows the trusted product winner before a cheaper untrusted headline',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);const db=database();appendObservation(db,null,obs('demo-northstar',53311,{matched_product_id:'demo-apple-mac-mini-m4-16-256',title:'Mac mini M4 16GB 256GB'}));appendObservation(db,null,obs('demo-marketsquare',47920,{matched_product_id:'demo-apple-mac-mini-m4-16-256',title:'Mac mini M4 16GB 256GB',shipping_minor:null}));const app=buildApp(db);const page=await app.inject({url:'/?q=Mac%20mini%20M4%2016GB%20256GB'});expect(page.body.indexOf('Northstar Retail')).toBeLessThan(page.body.indexOf('MarketSquare Seller'));await app.close()});
  it('exposes the flight vertical through the universal MCP tool',async()=>{vi.stubEnv('PRICEMCP_DATASET',demoDataset);const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();const server=createMcpServer(database());const client=new Client({name:'demo-flight-test',version:'1'});await server.connect(serverTransport);await client.connect(clientTransport);const called=await client.callTool({name:'search_price',arguments:{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'}});expect(called.structuredContent).toMatchObject({status:'ok',synthetic:true,best_offer:{provider:{name:'United'},quote:{total_minor:61200}}});await client.close();await server.close()});
});
