import { describe,expect,it,vi } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { openDatabase,seed,appendObservation } from '../src/db.js';
import { buildApp } from '../src/server.js';
import { createMcpServer } from '../src/mcp.js';
import type { RawObservation } from '../src/types.js';

const setup=()=>{const db=openDatabase(':memory:');seed(db);appendObservation(db,null,{source:'test',source_method:'fixture',merchant_id:'apple',source_product_id:'apple-sku',url:'https://apple.com/test',observed_at:new Date().toISOString(),title:'MacBook Air M5 13-inch 16GB 512GB',raw_price:'$1,299',currency:'USD',price_minor:129900,shipping_minor:0,available:true,condition:'new',matched_product_id:'apple-macbook-air-m5-13-16-512',match_confidence:.99,collection_status:'success'} as RawObservation);return db};

describe('REST and website',()=>{
  it('serves search, product, offers, history, compare and best-price',async()=>{const app=buildApp(setup());for(const url of ['/v1/search?q=MacBook%20Air%20M5%2016GB%20512GB','/v1/products/apple-macbook-air-m5-13-16-512','/v1/products/apple-macbook-air-m5-13-16-512/offers','/v1/products/apple-macbook-air-m5-13-16-512/history','/v1/compare?ids=apple-macbook-air-m5-13-16-512','/v1/best-price/apple-macbook-air-m5-13-16-512']){const r=await app.inject({url});expect(r.statusCode,url).toBe(200);expect(r.json(),url).toBeTruthy()}await app.close()});
  it('accepts freshness thresholds in seconds and excludes older offers',async()=>{const app=buildApp(setup());const r=await app.inject({url:'/v1/products/apple-macbook-air-m5-13-16-512/offers?max_age=1'});expect(r.statusCode).toBe(200);expect(r.json().max_age_seconds).toBe(1);await app.close()});
  it('returns explicit schema-complete not-implemented responses when no flight query is supplied',async()=>{const app=buildApp(setup());for(const category of ['fx','flights']){const r=await app.inject({url:`/v1/${category}`});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({status:'not_implemented',data:null})}await app.close()});
  it('fails closed instead of inventing a live flight fare without a configured provider',async()=>{vi.stubEnv('AMADEUS_API_KEY','');vi.stubEnv('AMADEUS_API_SECRET','');const app=buildApp(setup());const r=await app.inject({method:'POST',url:'/v1/search-price',payload:{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'}});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({status:'not_configured',offers:[],synthetic:false});await app.close();vi.unstubAllEnvs()});
  it('rejects incomplete universal search subjects before invoking a provider',async()=>{const app=buildApp(setup());for(const payload of [{type:'product',query:''},{type:'flight',origin:'WAS',destination:'BER'},{type:'flight',origin:'WAS',destination:'BER',departure_date:'09/18/2026'},{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-02-31'},{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',cabin:'coach'}]){const r=await app.inject({method:'POST',url:'/v1/search-price',payload});expect(r.statusCode).toBe(400);expect(r.json()).toMatchObject({status:'invalid_request'})}expect((await app.inject({method:'POST',url:'/v1/search-price?max_age=-1',payload:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}})).statusCode).toBe(400);await app.close()});
  it('renders product evidence in the website',async()=>{const app=buildApp(setup());const r=await app.inject({url:'/products/apple-macbook-air-m5-13-16-512'});expect(r.statusCode).toBe(200);expect(r.body).toContain('Best trusted price');expect(r.body).toContain('Source ↗');await app.close()});
  it('proves the infrastructure through a real read-only MCP diagnostic path',async()=>{const app=buildApp(setup(),{readOnly:true});const page=await app.inject({url:'/developer'});expect(page.statusCode).toBe(200);expect(page.body).toContain('Watch the price layer work.');expect(page.body).toContain('Run live 5-store product query');const listed=await app.inject({url:'/v1/mcp/tools'});expect(listed.statusCode).toBe(200);expect(listed.json()).toMatchObject({protocol:'MCP',server:'PriceMCP',read_only:true});expect(listed.json().tools.map((tool:any)=>tool.name)).toContain('search_price');expect(listed.json().tools.map((tool:any)=>tool.name)).not.toContain('record_decision');const invoked=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',arguments:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}}});expect(invoked.statusCode).toBe(200);expect(invoked.json()).toMatchObject({protocol:'MCP',tool:'search_price',mode:'live_snapshot',response:{status:'ok',subject:{product_id:'apple-macbook-air-m5-13-16-512'}},trace:{canonical_identity:'apple-macbook-air-m5-13-16-512',provider_count:1,provenance_urls:1}});const blocked=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'record_decision',arguments:{}}});expect(blocked.statusCode).toBe(400);await app.close()});
  it('runs the cross-domain flight fixture through MCP only when explicitly disclosed',async()=>{vi.stubEnv('AMADEUS_API_KEY','must-not-be-used');vi.stubEnv('AMADEUS_API_SECRET','must-not-be-used');const app=buildApp(setup(),{readOnly:true});const flight=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',demo:true,arguments:{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'}}});expect(flight.statusCode).toBe(200);expect(flight.json()).toMatchObject({protocol:'MCP',mode:'synthetic_flight_fixture',response:{status:'ok',synthetic:true,dataset:'pricemcp-demo-v1',subject:{type:'flight',origin:'WAS',destination:'BER'}},trace:{canonical_identity:'WAS-BER',provider_count:3}});const misuse=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',demo:true,arguments:{type:'product',query:'MacBook'}}});expect(misuse.statusCode).toBe(400);await app.close();vi.unstubAllEnvs()});
  it('enforces optional bearer auth while leaving machine health readable',async()=>{vi.stubEnv('PRICEMCP_API_TOKEN','test-secret');const app=buildApp(setup());expect((await app.inject({url:'/v1/search?q=MacBook'})).statusCode).toBe(401);expect((await app.inject({url:'/v1/search?q=MacBook',headers:{authorization:'Bearer test-secret'}})).statusCode).toBe(200);expect((await app.inject({url:'/internal/health'})).statusCode).toBe(200);await app.close();vi.unstubAllEnvs()});
  it('serves reads without seeding or mutating a query-only production snapshot',async()=>{const db=setup();db.exec('PRAGMA query_only=ON');const app=buildApp(db,{readOnly:true});expect((await app.inject({url:'/v1/search?q=MacBook'})).statusCode).toBe(200);expect(()=>db.prepare("INSERT INTO schema_meta(key,value) VALUES('blocked','true')").run()).toThrow(/read.?only/i);await app.close()});
});

describe('MCP',()=>{
  it('lists and calls concise deterministic structured tools against the same database',async()=>{const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();const server=createMcpServer(setup());const client=new Client({name:'test',version:'1'});await server.connect(serverTransport);await client.connect(clientTransport);const tools=await client.listTools();expect(tools.tools.map(t=>t.name)).toEqual(expect.arrayContaining(['search_price','search_products','get_price','compare_prices','find_best_offer','get_price_history','list_decisions','record_decision']));expect(tools.tools.find(t=>t.name==='record_decision')?.annotations).toMatchObject({readOnlyHint:false,destructiveHint:true});const invalid=await client.callTool({name:'search_price',arguments:{type:'product'}});expect(invalid.structuredContent).toMatchObject({status:'invalid_request'});const generic=await client.callTool({name:'search_price',arguments:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}});expect(generic.structuredContent).toMatchObject({status:'ok',subject:{type:'product',product_id:'apple-macbook-air-m5-13-16-512'},best_offer:{provider:{provider_id:'apple'}}});const called=await client.callTool({name:'find_best_offer',arguments:{query:'MacBook Air M5 13 16GB 512GB',trusted_only:true,max_age_hours:6}});const data=called.structuredContent as any;expect(data.resolved_product.product_id).toBe('apple-macbook-air-m5-13-16-512');expect(data.best_offer.merchant.merchant_id).toBe('apple');expect(data.best_offer.quote.effective_amount_minor).toBe(129900);expect(data.resolved_product).not.toHaveProperty('attributes_json');expect(data.best_offer).not.toHaveProperty('observation_id');const recorded=await client.callTool({name:'record_decision',arguments:{product_id:'apple-macbook-air-m5-13-16-512',merchant_id:'apple',rationale:'Approved test decision with fresh evidence.'}});expect(recorded.structuredContent).toMatchObject({status:'recorded',decision:{product_id:'apple-macbook-air-m5-13-16-512'}});await client.close();await server.close()});
  it('removes the write tool from read-only deployments',async()=>{const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();const server=createMcpServer(setup(),{allowWrites:false});const client=new Client({name:'test',version:'1'});await server.connect(serverTransport);await client.connect(clientTransport);const tools=await client.listTools();expect(tools.tools.map(t=>t.name)).not.toContain('record_decision');expect(tools.tools.map(t=>t.name)).toEqual(expect.arrayContaining(['search_price','compare_prices','list_decisions']));await client.close();await server.close()});
});
