import { describe,expect,it,vi } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { openDatabase,seed,appendObservation } from '../src/db.js';
import { buildApp } from '../src/server.js';
import { createMcpServer } from '../src/mcp.js';
import type { RawObservation } from '../src/types.js';

const setup=()=>{const db=openDatabase(':memory:');seed(db);appendObservation(db,null,{source:'test',source_method:'fixture',merchant_id:'apple',source_product_id:'apple-sku',url:'https://apple.com/test',observed_at:new Date().toISOString(),title:'MacBook Air M5 13-inch 16GB 512GB',raw_price:'$1,299',currency:'USD',price_minor:129900,shipping_minor:0,available:true,condition:'new',matched_product_id:'apple-macbook-air-m5-13-16-512',match_confidence:.99,collection_status:'success'} as RawObservation);return db};

describe('REST and website',()=>{
  it('makes category bubbles reveal every matching variation in view',async()=>{const app=buildApp(setup(),{readOnly:true});const r=await app.inject({url:'/cheap-apples'});expect(r.statusCode).toBe(200);expect(r.body).toContain("const showCategory=button=>");expect(r.body).toContain("input.value=''");expect(r.body).toContain("window.scrollTo({top:Math.max(0,top),behavior:'smooth'})");expect(r.body).toContain("setAttribute('aria-pressed'");await app.close()});
  it('shows consumer shopping details without inventing delivery timing',async()=>{const app=buildApp(setup(),{readOnly:true});for(const url of ['/cheap-apples','/cheap-apples/apple-macbook-air-m5-13-16-512']){const r=await app.inject({url});expect(r.statusCode).toBe(200);expect(r.body).toContain('Online shop');expect(r.body).toContain('Last updated');expect(r.body).toContain('Delivery time');expect(r.body).toContain('See at checkout');if(url==='/cheap-apples')expect((r.body.match(/Delivery time/g)||[]).length).toBeGreaterThanOrEqual(3)}await app.close()});
  it('serves search, product, offers, history, compare and best-price',async()=>{const app=buildApp(setup());for(const url of ['/v1/search?q=MacBook%20Air%20M5%2016GB%20512GB','/v1/products/apple-macbook-air-m5-13-16-512','/v1/products/apple-macbook-air-m5-13-16-512/offers','/v1/products/apple-macbook-air-m5-13-16-512/history','/v1/compare?ids=apple-macbook-air-m5-13-16-512','/v1/best-price/apple-macbook-air-m5-13-16-512']){const r=await app.inject({url});expect(r.statusCode,url).toBe(200);expect(r.json(),url).toBeTruthy()}await app.close()});
  it('accepts freshness thresholds in seconds and excludes older offers',async()=>{const app=buildApp(setup());const r=await app.inject({url:'/v1/products/apple-macbook-air-m5-13-16-512/offers?max_age=1'});expect(r.statusCode).toBe(200);expect(r.json().max_age_seconds).toBe(1);await app.close()});
  it('publishes the machine-readable core catalog and implementation boundaries',async()=>{const app=buildApp(setup());const r=await app.inject({url:'/v1/catalog'});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({version:'2026-09-03'});expect(r.json().contracts).toEqual(expect.arrayContaining([expect.objectContaining({type:'product',state:'live'}),expect.objectContaining({type:'flight',state:'provider_ready'}),expect.objectContaining({type:'stay',state:'contract_ready'})]));expect(r.json().transaction_boundary).toContain('does not claim in-app booking');await app.close()});
  it('returns explicit schema-complete not-implemented responses when no flight query is supplied',async()=>{const app=buildApp(setup());for(const category of ['fx','flights']){const r=await app.inject({url:`/v1/${category}`});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({status:'not_implemented',data:null})}await app.close()});
  it('fails closed instead of inventing a live flight fare without a configured provider',async()=>{vi.stubEnv('AMADEUS_API_KEY','');vi.stubEnv('AMADEUS_API_SECRET','');const app=buildApp(setup());const r=await app.inject({method:'POST',url:'/v1/search-price',payload:{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'}});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({status:'not_configured',offers:[],synthetic:false});await app.close();vi.unstubAllEnvs()});
  it('rejects incomplete universal search subjects before invoking a provider',async()=>{const app=buildApp(setup());for(const payload of [{type:'product',query:''},{type:'flight',origin:'WAS',destination:'BER'},{type:'flight',origin:'WAS',destination:'BER',departure_date:'09/18/2026'},{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-02-31'},{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',cabin:'coach'}]){const r=await app.inject({method:'POST',url:'/v1/search-price',payload});expect(r.statusCode).toBe(400);expect(r.json()).toMatchObject({status:'invalid_request'})}expect((await app.inject({method:'POST',url:'/v1/search-price?max_age=-1',payload:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}})).statusCode).toBe(400);await app.close()});
  it('renders a saveable, recheckable product decision with a safe provider handoff',async()=>{const app=buildApp(setup());const r=await app.inject({url:'/products/apple-macbook-air-m5-13-16-512'});expect(r.statusCode).toBe(200);expect(r.body).toContain('Best trusted price');expect(r.body).toContain('Source ↗');expect(r.body).toContain('Save this decision');expect(r.body).toContain('Recheck evidence');expect(r.body).toContain('id="winner-source"');expect(r.body).toContain('Check at Apple ↗');expect(r.body).toContain("!initial.synthetic&&current.synthetic!==true");expect(r.body).toContain("safeWinnerUrl(current.source&&current.source.url)");expect(r.body).toContain("winnerSource.removeAttribute('href')");expect(r.body).toContain('pricemcp-product-decisions-v1');expect(r.body).toContain("tool:'search_price'");expect(r.body).toContain('Check before buying');expect(r.body).toContain('Destination tax');await app.close()});
  it('serves a private browser-local decision watchlist with safe rechecks',async()=>{const app=buildApp(setup());const r=await app.inject({url:'/decisions'});expect(r.statusCode).toBe(200);expect(r.body).toContain('Your decision watchlist');expect(r.body).toContain('PriceMCP does not upload them');expect(r.body).toContain('pricemcp-product-decisions-v1');expect(r.body).toContain('Recheck all');expect(r.body).toContain("fetch('/v1/mcp/search'");expect(r.body).toContain("url.protocol==='https:'");expect(r.body).toContain('PRICE DOWN');expect(r.body).toContain('NO CURRENT OFFER');expect(r.body).toContain("evidence.href='/products/'");await app.close()});
  it('does not render executable product evidence links',async()=>{const db=setup();appendObservation(db,null,{source:'unsafe-page-test',source_method:'fixture',merchant_id:'apple',source_product_id:'unsafe-page-sku',url:'javascript:alert(1)',observed_at:new Date().toISOString(),title:'MacBook Air M5 13-inch 16GB 512GB',raw_price:'$1,199',currency:'USD',price_minor:119900,shipping_minor:0,available:true,condition:'new',matched_product_id:'apple-macbook-air-m5-13-16-512',match_confidence:.99,collection_status:'success'} as RawObservation);const app=buildApp(db);const r=await app.inject({url:'/products/apple-macbook-air-m5-13-16-512'});expect(r.statusCode).toBe(200);expect(r.body).not.toContain('href="javascript:');expect(r.body).toContain('No safe public source URL');await app.close()});
  it('serves a product-first consumer Companion with safe decision actions',async()=>{const app=buildApp(setup(),{readOnly:true});const r=await app.inject({url:'/companion?q=I%20need%20MacBook%20Air%20M5%2013-inch%2016GB%20512GB%20under%20%241500'});expect(r.statusCode).toBe(200);expect(r.body).toContain('Tell me what you’re buying.');expect(r.body).toContain('LIVE PRODUCT EVIDENCE');expect(r.body).toContain('I need MacBook Air M5 13-inch 16GB 512GB under $1500');expect(r.body).toContain("fetch('/v1/mcp/search'");expect(r.body).toContain('READY TO DECIDE');expect(r.body).toContain('INSUFFICIENT EVIDENCE');expect(r.body).toContain('Continue to retailer');expect(r.body).toContain("url.protocol==='https:'");expect(r.body).toContain('pricemcp-product-decisions-v1');expect(r.body).toContain('/companion/flights');await app.close()});
  it('serves Cheap Apples as a B2C storefront with every active catalog product',async()=>{const app=buildApp(setup(),{readOnly:true});const r=await app.inject({url:'/cheap-apples'});expect(r.statusCode).toBe(200);expect(r.body).toContain('<title>Cheap Apples — better Apple prices</title>');expect(r.body).toContain('Apple prices,');expect(r.body).toContain('picked clean.');expect(r.body).toContain('id="ca-hero-search"');expect(r.body).toContain('MacBook Air M5 13-inch 16GB/512GB');expect(r.body).toContain('TODAY’S PICK');expect(r.body).not.toContain('BEST DROP');expect(r.body).toContain('Today’s pick');expect(r.body).toContain('Find your Apple.');expect(r.body).toContain('37 current configurations');expect((r.body.match(/class="ca-product"/g)||[])).toHaveLength(37);expect(r.body).toContain('data-category="phone"');expect(r.body).toContain('data-category="live"');expect(r.body).toContain('CHECKING SOON');expect(r.body).not.toContain('MacBook Air M4 13-inch 16GB/256GB');expect(r.body).toContain('Saved');expect(r.body).toContain('Prices checked independently');expect(r.body).not.toContain('PriceMCP');expect(r.body).toContain('Not affiliated with or endorsed by Apple Inc.');await app.close()});
  it('preserves the detailed flight Companion as a separate, disclosed lab',async()=>{vi.stubEnv('DUFFEL_ACCESS_TOKEN','duffel_test_token');vi.stubEnv('DUFFEL_ENV','test');const app=buildApp(setup(),{readOnly:true});const r=await app.inject({url:'/companion/flights'});expect(r.statusCode).toBe(200);expect(r.body).toContain('PriceMCP Companion');expect(r.body).toContain('Sandbox connected');expect(r.body).toContain('SANDBOX READY');expect(r.body).toContain("fetch('/v1/mcp/invoke'");expect(r.body).toContain("JSON.stringify({tool:'search_price',arguments:subject})");expect(r.body).toContain('Trip type');expect(r.body).toContain('Adult travelers');expect(r.body).toContain('Premium economy');expect(r.body).toContain('Shortest travel time');expect(r.body).toContain('Offer details');expect(r.body).toContain('Recheck saved prices');expect(r.body).toContain("latest=null");expect(r.body).toContain("currency changed '+old.currency+' → '");expect(r.body).toContain('stopCount(offer)===0');expect(r.body).toContain('Continue with provider');expect(r.body).toContain('disabled');expect(r.body).toContain('Booking remains disabled');await app.close();vi.unstubAllEnvs()});
  it('tells flight-lab users when no provider is configured',async()=>{vi.stubEnv('DUFFEL_ACCESS_TOKEN','');vi.stubEnv('AMADEUS_API_KEY','');vi.stubEnv('AMADEUS_API_SECRET','');const app=buildApp(setup(),{readOnly:true});const r=await app.inject({url:'/companion/flights'});expect(r.body).toContain('Provider not configured');expect(r.body).toContain('NOT CONFIGURED');expect(r.body).toContain('fail closed');await app.close();vi.unstubAllEnvs()});
  it('proves the infrastructure through a real read-only MCP diagnostic path',async()=>{const app=buildApp(setup(),{readOnly:true});const page=await app.inject({url:'/developer'});expect(page.statusCode).toBe(200);expect(page.body).toContain('Watch the price layer work.');expect(page.body).toContain('Run live 5-store product query');const listed=await app.inject({url:'/v1/mcp/tools'});expect(listed.statusCode).toBe(200);expect(listed.json()).toMatchObject({protocol:'MCP',server:'PriceMCP',read_only:true});expect(listed.json().tools.map((tool:any)=>tool.name)).toContain('search_price');expect(listed.json().tools.map((tool:any)=>tool.name)).not.toContain('record_decision');const invoked=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',arguments:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}}});expect(invoked.statusCode).toBe(200);expect(invoked.json()).toMatchObject({protocol:'MCP',tool:'search_price',mode:'live_snapshot',response:{status:'ok',subject:{product_id:'apple-macbook-air-m5-13-16-512'}},trace:{canonical_identity:'apple-macbook-air-m5-13-16-512',provider_count:1,provenance_urls:1}});const blocked=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'record_decision',arguments:{}}});expect(blocked.statusCode).toBe(400);await app.close()});
  it('backs the homepage activity stream with a real natural-language MCP request',async()=>{const app=buildApp(setup(),{readOnly:true});const page=await app.inject({url:'/'});expect(page.statusCode).toBe(200);expect(page.body).toContain('Live MCP activity');expect(page.body).toContain('/v1/mcp/search');const traced=await app.inject({method:'POST',url:'/v1/mcp/search',payload:{query:'MacBook Air M5 13 16GB 512GB'}});expect(traced.statusCode).toBe(200);expect(traced.json()).toMatchObject({protocol:'MCP',tool:'search_price',mode:'live_snapshot',request:{type:'product',query:'MacBook Air M5 13 16GB 512GB'},response:{status:'ok'},trace:{canonical_identity:'apple-macbook-air-m5-13-16-512',normalized_offer_count:1,provider_count:1}});const incomplete=await app.inject({method:'POST',url:'/v1/mcp/search',payload:{query:'find flight prices'}});expect(incomplete.statusCode).toBe(400);expect(incomplete.json()).toMatchObject({status:'invalid_request'});await app.close()});
  it('gives live visitors a direct Companion, decision, and watchlist path',async()=>{const app=buildApp(setup(),{readOnly:true});const page=await app.inject({url:'/'});expect(page.statusCode).toBe(200);expect(page.body).toContain('Start with a real decision');expect(page.body).toContain('Compare something PriceMCP can verify today.');expect(page.body).toContain('href="/companion?q=I%20need%20AirPods%20Pro%203%20under%20%24300"');expect(page.body).toContain('href="/products/apple-airpods-pro-3"');expect(page.body).toContain('href="/decisions"');expect(page.body).toContain('Tell Companion what you need');expect(page.body).toContain('form.after(firstDecision)');await app.close()});
  it('registers concise read-only browser WebMCP tools on every page',async()=>{const app=buildApp(setup(),{readOnly:true});for(const url of ['/','/developer','/products/apple-macbook-air-m5-13-16-512']){const page=await app.inject({url});expect(page.statusCode).toBe(200);expect(page.body).toContain('document.modelContext.registerTool');expect(page.body).toContain("name:'find_best_price'");expect(page.body).toContain("name:'inspect_price_evidence'");expect(page.body).toContain("name:'run_flight_price_demo'");expect(page.body).toContain('readOnlyHint:true');expect(page.body).toContain('untrustedContentHint:true');expect(page.body).toContain("signal});");expect(page.body).toContain('Synthetic demonstration; not live, purchasable, or bookable.')}await app.close()});
  it('labels the recorded hackathon partner proof separately from live price data',async()=>{const app=buildApp(setup(),{readOnly:true});const page=await app.inject({url:'/'});expect(page.body).toContain('Live MCP + partner proof feed');expect(page.body).toContain('Bright Data');expect(page.body).toContain('TrueForge');expect(page.body).toContain('Qodo');const proof=await app.inject({url:'/v1/hackathon-partners'});expect(proof.statusCode).toBe(200);expect(proof.json()).toMatchObject({status:'verified_submission_evidence',partners:[{name:'Bright Data',state:'verified'},{name:'TrueForge',state:'verified'},{name:'Qodo',state:'verified'}]});expect(proof.json().boundary).toContain('recorded submission evidence');await app.close()});
  it('runs the cross-domain flight fixture through MCP only when explicitly disclosed',async()=>{vi.stubEnv('AMADEUS_API_KEY','must-not-be-used');vi.stubEnv('AMADEUS_API_SECRET','must-not-be-used');const app=buildApp(setup(),{readOnly:true});const flight=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',demo:true,arguments:{type:'flight',origin:'WAS',destination:'BER',departure_date:'2026-09-18',return_date:'2026-09-25'}}});expect(flight.statusCode).toBe(200);expect(flight.json()).toMatchObject({protocol:'MCP',mode:'synthetic_flight_fixture',response:{status:'ok',synthetic:true,dataset:'pricemcp-demo-v1',subject:{type:'flight',origin:'WAS',destination:'BER'}},trace:{canonical_identity:'WAS-BER',provider_count:3}});const misuse=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',demo:true,arguments:{type:'product',query:'MacBook'}}});expect(misuse.statusCode).toBe(400);await app.close();vi.unstubAllEnvs()});
  it('enforces optional bearer auth while leaving machine health readable',async()=>{vi.stubEnv('PRICEMCP_API_TOKEN','test-secret');const app=buildApp(setup());expect((await app.inject({url:'/v1/search?q=MacBook'})).statusCode).toBe(401);expect((await app.inject({url:'/v1/search?q=MacBook',headers:{authorization:'Bearer test-secret'}})).statusCode).toBe(200);expect((await app.inject({url:'/internal/health'})).statusCode).toBe(200);await app.close();vi.unstubAllEnvs()});
  it('keeps only the read-only public console reachable when bearer auth is enabled',async()=>{vi.stubEnv('PRICEMCP_API_TOKEN','test-secret');const app=buildApp(setup(),{readOnly:true});expect((await app.inject({url:'/developer'})).statusCode).toBe(200);expect((await app.inject({url:'/v1/mcp/tools'})).statusCode).toBe(200);expect((await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',arguments:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}}})).statusCode).toBe(200);expect((await app.inject({url:'/v1/search?q=MacBook'})).statusCode).toBe(401);await app.close();vi.unstubAllEnvs()});
  it('never exposes executable provenance URLs through the universal response',async()=>{const db=setup();appendObservation(db,null,{source:'unsafe-test',source_method:'fixture',merchant_id:'apple',source_product_id:'unsafe-sku',url:'javascript:alert(1)',observed_at:new Date().toISOString(),title:'MacBook Air M5 13-inch 16GB 512GB',raw_price:'$999',currency:'USD',price_minor:99900,shipping_minor:0,available:true,condition:'new',matched_product_id:'apple-macbook-air-m5-13-16-512',match_confidence:.99,collection_status:'success'} as RawObservation);const app=buildApp(db,{readOnly:true});const invoked=await app.inject({method:'POST',url:'/v1/mcp/invoke',payload:{tool:'search_price',arguments:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}}});expect(invoked.statusCode).toBe(200);const unsafe=invoked.json().response.offers.find((offer:any)=>offer.source.source_product_id==='unsafe-sku');expect(unsafe.source.url).toBeNull();await app.close()});
  it('serves reads without seeding or mutating a query-only production snapshot',async()=>{const db=setup();db.exec('PRAGMA query_only=ON');const app=buildApp(db,{readOnly:true});expect((await app.inject({url:'/v1/search?q=MacBook'})).statusCode).toBe(200);expect(()=>db.prepare("INSERT INTO schema_meta(key,value) VALUES('blocked','true')").run()).toThrow(/read.?only/i);await app.close()});
});

describe('Cheap Apples consumer journey',()=>{
  it('keeps the shopping journey consumer-first from catalog to store',async()=>{
    const app=buildApp(setup(),{readOnly:true});
    const page=await app.inject({url:'/cheap-apples/apple-macbook-air-m5-13-16-512'});
    expect(page.statusCode).toBe(200);
    expect(page.body).toContain('<title>MacBook Air M5 13-inch 16GB/512GB price — Cheap Apples</title>');
    expect(page.body).toContain('Best price today');
    expect(page.body).toContain('Shop at Apple ↗');
    expect(page.body).toContain('Save this price');
    expect(page.body).toContain('Check price again');
    expect(page.body).toContain('Why this is our pick');
    expect(page.body).toContain('Before you buy:');
    expect(page.body).toContain("fetch('/v1/search-price'");
    expect(page.body).toContain("url.protocol==='https:'");
    expect(page.body).not.toContain('verdict');
    expect(page.body).not.toContain('PriceMCP');
    await app.close();
  });
  it('has its own plain-language saved-price page',async()=>{
    const app=buildApp(setup(),{readOnly:true});
    const page=await app.inject({url:'/cheap-apples/saved'});
    expect(page.statusCode).toBe(200);
    expect(page.body).toContain('<title>Saved prices — Cheap Apples</title>');
    expect(page.body).toContain('Your saved prices.');
    expect(page.body).toContain('Check all prices');
    expect(page.body).toContain("fetch('/v1/search-price'");
    expect(page.body).toContain("details.href='/cheap-apples/'");
    expect(page.body).not.toContain('evidence');
    expect(page.body).not.toContain('verdict');
    expect(page.body).not.toContain('PriceMCP');
    await app.close();
  });
});

describe('MCP',()=>{
  it('lists and calls concise deterministic structured tools against the same database',async()=>{const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();const server=createMcpServer(setup());const client=new Client({name:'test',version:'1'});await server.connect(serverTransport);await client.connect(clientTransport);const tools=await client.listTools();expect(tools.tools.map(t=>t.name)).toEqual(expect.arrayContaining(['list_catalog','search_price','search_products','get_price','compare_prices','find_best_offer','get_price_history','list_decisions','record_decision']));expect(tools.tools.find(t=>t.name==='record_decision')?.annotations).toMatchObject({readOnlyHint:false,destructiveHint:true});const catalog=await client.callTool({name:'list_catalog',arguments:{}});expect((catalog.structuredContent as any).contracts).toEqual(expect.arrayContaining([expect.objectContaining({type:'product',state:'live'}),expect.objectContaining({type:'flight',state:'provider_ready'}),expect.objectContaining({type:'stay',state:'contract_ready'})]));const invalid=await client.callTool({name:'search_price',arguments:{type:'product'}});expect(invalid.structuredContent).toMatchObject({status:'invalid_request'});const generic=await client.callTool({name:'search_price',arguments:{type:'product',query:'MacBook Air M5 13 16GB 512GB'}});expect(generic.structuredContent).toMatchObject({status:'ok',subject:{type:'product',product_id:'apple-macbook-air-m5-13-16-512'},best_offer:{provider:{provider_id:'apple'}}});const called=await client.callTool({name:'find_best_offer',arguments:{query:'MacBook Air M5 13 16GB 512GB',trusted_only:true,max_age_hours:6}});const data=called.structuredContent as any;expect(data.resolved_product.product_id).toBe('apple-macbook-air-m5-13-16-512');expect(data.best_offer.merchant.merchant_id).toBe('apple');expect(data.best_offer.quote.effective_amount_minor).toBe(129900);expect(data.resolved_product).not.toHaveProperty('attributes_json');expect(data.best_offer).not.toHaveProperty('observation_id');const recorded=await client.callTool({name:'record_decision',arguments:{product_id:'apple-macbook-air-m5-13-16-512',merchant_id:'apple',rationale:'Approved test decision with fresh evidence.'}});expect(recorded.structuredContent).toMatchObject({status:'recorded',decision:{product_id:'apple-macbook-air-m5-13-16-512'}});await client.close();await server.close()});
  it('removes the write tool from read-only deployments',async()=>{const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();const server=createMcpServer(setup(),{allowWrites:false});const client=new Client({name:'test',version:'1'});await server.connect(serverTransport);await client.connect(clientTransport);const tools=await client.listTools();expect(tools.tools.map(t=>t.name)).not.toContain('record_decision');expect(tools.tools.map(t=>t.name)).toEqual(expect.arrayContaining(['search_price','compare_prices','list_decisions']));await client.close();await server.close()});
});
